// @generated by Hollywood. Do not edit by hand.

import { runGitHubAction } from "@dedalus-labs/hollywood/action-runtime";
import { listWheels } from "../../../../../ci/artifacts.ts";

void runGitHubAction(listWheels);
