from collections.abc import Iterator, Sequence
from typing import TypeAlias, overload

from typing_extensions import Self

_Shape: TypeAlias = int | tuple[_Shape, ...]
_Offset: TypeAlias = int | F2 | ArithTuple
_Stride: TypeAlias = _Offset | tuple[_Stride, ...]
_Coordinate: TypeAlias = int | tuple[_Coordinate, ...]
_XorCoordinate: TypeAlias = F2 | tuple[_XorCoordinate, ...]
_Slicing: TypeAlias = int | None | slice | tuple[_Slicing, ...]
_Tiler: TypeAlias = int | Layout | None | tuple[_Tiler, ...]

class LayoutError(ValueError): ...

class F2:
    def __new__(cls, value: int | F2) -> F2: ...
    @property
    def value(self) -> int: ...
    def __int__(self) -> int: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __lt__(self, other: int | F2) -> bool: ...
    def __le__(self, other: int | F2) -> bool: ...
    def __gt__(self, other: int | F2) -> bool: ...
    def __ge__(self, other: int | F2) -> bool: ...
    def __add__(self, other: int | F2) -> F2: ...
    def __radd__(self, other: int | F2) -> F2: ...
    def __sub__(self, other: int | F2) -> F2: ...
    def __rsub__(self, other: int | F2) -> F2: ...
    def __neg__(self) -> F2: ...
    def __mul__(self, other: int | F2) -> F2: ...
    def __rmul__(self, other: int | F2) -> F2: ...

class ArithTuple:
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> int | ArithTuple: ...
    def __iter__(self) -> Iterator[int | ArithTuple]: ...
    def __eq__(self, other: object) -> bool: ...
    def __lt__(self, other: int | ArithTuple | tuple[int, ...]) -> bool: ...
    def __le__(self, other: int | ArithTuple | tuple[int, ...]) -> bool: ...
    def __gt__(self, other: int | ArithTuple | tuple[int, ...]) -> bool: ...
    def __ge__(self, other: int | ArithTuple | tuple[int, ...]) -> bool: ...
    def __add__(
        self, other: int | ArithTuple | tuple[int, ...]
    ) -> int | ArithTuple: ...
    def __radd__(
        self, other: int | ArithTuple | tuple[int, ...]
    ) -> int | ArithTuple: ...
    def __sub__(
        self, other: int | ArithTuple | tuple[int, ...]
    ) -> int | ArithTuple: ...
    def __rsub__(
        self, other: int | ArithTuple | tuple[int, ...]
    ) -> int | ArithTuple: ...
    def __neg__(self) -> ArithTuple: ...
    def __mul__(self, other: int) -> int | ArithTuple: ...
    def __rmul__(self, other: int) -> int | ArithTuple: ...

class Layout:
    def __new__(cls, shape: _Shape, stride: _Stride) -> Layout: ...
    @staticmethod
    def from_modes(modes: Sequence[Layout]) -> Layout: ...
    @staticmethod
    def from_tiler(tiler: _Tiler) -> Layout: ...
    @property
    def shape(self) -> _Shape: ...
    @property
    def stride(self) -> _Stride: ...
    @property
    def rank(self) -> int: ...
    @property
    def depth(self) -> int: ...
    def coshape(self) -> _Shape: ...
    def get(self, path: Sequence[int]) -> Layout: ...
    def __call__(self, coordinate: _Coordinate | F2 | ArithTuple) -> _Offset: ...
    def slice(self, coordinate: _Slicing) -> tuple[_Offset, Layout]: ...
    def coalesce(self) -> Layout: ...
    def compose(self, tiler: _Tiler) -> Layout: ...
    def logical_divide(self, tiler: _Tiler) -> Layout: ...
    def zipped_divide(self, tiler: _Tiler) -> Layout: ...
    def logical_product(self, tiler: _Tiler) -> Layout: ...
    def blocked_product(self, tile: Layout) -> Layout: ...
    def raked_product(self, tile: Layout) -> Layout: ...
    def complement(self, cotarget: _Shape | None = None) -> Layout: ...
    def right_inverse(self) -> Layout: ...
    def left_inverse(self) -> Layout: ...
    def nullspace(self) -> Layout: ...
    def recast(self, scale: _Shape) -> Layout: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class Swizzle:
    def __new__(cls, bits: int, base: int, shift: int) -> Self: ...
    @property
    def bits(self) -> int: ...
    @property
    def base(self) -> int: ...
    @property
    def shift(self) -> int: ...
    def __call__(self, index: int) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

def basis(path: Sequence[int]) -> int | ArithTuple: ...
@overload
def idx2crd(coordinate: F2, shape: _Shape) -> _XorCoordinate: ...
@overload
def idx2crd(coordinate: _Coordinate, shape: _Shape) -> _Coordinate: ...
def crd2idx(coordinate: _Coordinate, shape: _Shape) -> int: ...
def compatible(a: _Shape, b: _Shape) -> bool: ...
