// @generated by Hollywood. Do not edit by hand.

import { runGitHubAction } from "@dedalus-labs/hollywood/action-runtime";
import { affected } from "../../../../../ci/affected.ts";

void runGitHubAction(affected);
