# Copyright © 2026 Dedalus Labs, Inc.

"""Record every layout-algebra call that PyCuTe's own test suite makes.

PyCuTe (https://github.com/NVlabs/CuTe) is the reference implementation of the
layout algebra. Its tests exercise each operation on hand-picked layouts. This
pytest plugin wraps the public operations, runs those tests unchanged, and
writes each call with integer arguments to one line of ``cases.txt``:

    composition<TAB>(6, 2):(8, 2)<TAB>(4, 3):(3, 1)<TAB>=> ((2, 2), 3):((24, 2), 8)
    composition<TAB>(4, 6):(1, 4)<TAB>6:4<TAB>!! ValueError: Stride divisibility ...

``tests/reference.rs`` replays every line against tiki-cute. Calls with F2,
sympy or tensor arguments are skipped: F2 strides are not implemented, and
tiki-cute decides symbolic conditions from parameter facts rather than from
sympy's structural comparisons.

Regenerate from a PyCuTe checkout at the commit named in cases.txt:

    PYTHONPATH=<this directory> RECORD_OUT=<this directory>/cases.txt \\
      uv run --no-project --python 3.12 --with pytest --with sympy --with numpy \\
      python -m pytest -q -p record test
"""

import os
import subprocess

import pycute
from pycute import ArithTuple, Layout, basis_repr

OPERATIONS = [
    "coalesce",
    "coalesce_z",
    "composition",
    "complement",
    "right_inverse",
    "left_inverse",
    "nullspace",
    "logical_product",
    "logical_divide",
    "zipped_divide",
    "blocked_product",
    "raked_product",
    "recast",
    "make_layout_like",
    "make_ordered_layout",
    "layout_add",
]

cases = set()


class Unsupported(Exception):
    """An argument outside the integer layouts tiki-cute implements."""


def notation(value):
    """Return ``value`` in the CuTe notation tiki-cute parses."""
    if value is None:
        return "_"
    if type(value) is int:
        return str(value)
    if type(value) is ArithTuple:
        terms = []
        for coefficient, path in basis_repr(value):
            if type(coefficient) is not int:
                raise Unsupported(value)
            terms.append(
                str(coefficient) + "".join(f"@{mode}" for mode in reversed(path))
            )
        return "+".join(terms)
    if type(value) in (tuple, list):
        items = [notation(item) for item in value]
        return "(" + ", ".join(items) + ("," if len(items) == 1 else "") + ")"
    if type(value) is Layout:
        return f"{notation(value.shape)}:{notation(value.stride)}"
    raise Unsupported(value)


class Recorder:
    """Stands in for one operation and records its whole-layout calls."""

    def __init__(self, name, operation):
        self.name = name
        self.operation = operation

    def __getitem__(self, mode):
        return self.operation[mode]

    def __call__(self, *args, **kwargs):
        try:
            result = self.operation(*args, **kwargs)
        except (ValueError, TypeError) as error:
            self.record(args, kwargs, f"!! {type(error).__name__}: {error}")
            raise
        self.record(args, kwargs, result)
        return result

    def record(self, args, kwargs, outcome):
        if kwargs.get("mode", ()) != ():
            return
        name = self.name
        extend = kwargs.get(
            "extend", args[1] if name == "complement" and len(args) > 1 else None
        )
        if name == "complement":
            args = args[:1]
            if extend is not None:
                name, args = "complement_in", (args[0], extend)
        if name in ("coalesce", "coalesce_z") and (
            len(args) > 1 or "profile" in kwargs
        ):
            return
        try:
            if type(args[0]) is not Layout and name != "make_ordered_layout":
                raise Unsupported(args[0])
            fields = [notation(arg) for arg in args]
            result = outcome if isinstance(outcome, str) else "=> " + notation(outcome)
        except Unsupported:
            return
        cases.add("\t".join([name, *fields, result]))


def pytest_configure(config):
    for name in OPERATIONS:
        recorder = Recorder(name, getattr(pycute, name))
        for module in (pycute, pycute.algebra, pycute.layout):
            if hasattr(module, name):
                setattr(module, name, recorder)


def pytest_unconfigure(config):
    commit = subprocess.run(
        ["git", "rev-parse", "HEAD"], capture_output=True, text=True, check=True
    ).stdout.strip()
    with open(os.environ["RECORD_OUT"], "w") as out:
        out.write(
            f"# PyCuTe {commit}: every integer layout-algebra call its test suite makes.\n"
        )
        out.write("# Generated by record.py. Do not edit.\n")
        for case in sorted(cases):
            out.write(case.replace("\n", " ") + "\n")
