# Copyright © 2026 Dedalus Labs, Inc.

"""Tiki: CuTe-native layouts for MLX arrays.

A Tiki array follows the zop tensor model: an Engine paired with a first-class
CuTe ``Layout``, so ``tensor[coordinate] == engine[layout(coordinate)]``. The
layout algebra is NVIDIA's PyCuTe, vendored under ``_pycute`` and re-exported
here under zop's vocabulary. ``composed`` adds zop's ``outer o {offset} o inner``
form and its slicing invariant, which CuTe expresses differently.
"""

from mlx.tiki.composed import ComposedLayout, check_swizzle, slice_and_offset
from mlx.tiki.engine import ArrayEngine
from mlx.tiki.layout import (
    F2,
    Array,
    E,
    Engine,
    ImplicitAccessor,
    Layout,
    LayoutError,
    MutableEngine,
    Ptr,
    Swizzle,
    Tensor,
    TransformAccessor,
    basis,
    blocked_product,
    coalesce,
    compatible,
    complement,
    compose,
    congruent,
    coshape,
    cosize,
    crd2idx,
    depth,
    flatten,
    identity_tensor,
    idx2crd,
    is_layout,
    left_inverse,
    logical_divide,
    logical_product,
    make_layout,
    make_tensor,
    nullspace,
    raked_product,
    rank,
    recast,
    right_inverse,
    size,
    unflatten,
    zipped_divide,
)

__all__ = [
    "Array",
    "ArrayEngine",
    "ComposedLayout",
    "E",
    "Engine",
    "F2",
    "ImplicitAccessor",
    "Layout",
    "LayoutError",
    "MutableEngine",
    "Ptr",
    "Swizzle",
    "Tensor",
    "TransformAccessor",
    "basis",
    "check_swizzle",
    "blocked_product",
    "coalesce",
    "compatible",
    "complement",
    "compose",
    "congruent",
    "coshape",
    "cosize",
    "crd2idx",
    "depth",
    "flatten",
    "identity_tensor",
    "idx2crd",
    "is_layout",
    "left_inverse",
    "logical_divide",
    "logical_product",
    "make_layout",
    "make_tensor",
    "nullspace",
    "raked_product",
    "rank",
    "recast",
    "right_inverse",
    "size",
    "slice_and_offset",
    "unflatten",
    "zipped_divide",
]
