class LayoutError(ValueError): ...

class Swizzle:
    def __init__(self, bits: int, base: int, shift: int) -> None: ...
    @property
    def bits(self) -> int: ...
    @property
    def base(self) -> int: ...
    @property
    def shift(self) -> int: ...
    def __call__(self, index: int) -> int: ...
    def __hash__(self) -> int: ...
