#!/bin/sh
# Regenerate src/sys.rs, the CUDA driver API declarations the runtime calls.
# Usage: bindings.sh <cuda include dir>   (bindgen-cli 0.72.1, libclang on LIBCLANG_PATH)
set -eu

include=$1
crate=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
functions='cuInit|cuGetErrorName|cuGetErrorString|cuDeviceGetCount|cuDeviceGet|cuDeviceGetAttribute'
functions="$functions|cuDevicePrimaryCtxRetain|cuCtxPushCurrent|cuCtxPopCurrent"
functions="$functions|cuDeviceGetDefaultMemPool|cuMemPoolGetAttribute|cuMemGetInfo"
functions="$functions|cuStreamCreate|cuStreamDestroy|cuStreamSynchronize|cuStreamWaitEvent"
functions="$functions|cuMemAlloc|cuMemAllocAsync|cuMemFree|cuMemFreeAsync|cuMemsetD8Async"
functions="$functions|cuMemcpyHtoDAsync|cuMemcpyDtoHAsync|cuMemcpyDtoDAsync"
functions="$functions|cuEventCreate|cuEventDestroy|cuEventRecord|cuEventQuery|cuEventSynchronize"
functions="$functions|cuLaunchHostFunc"

{
    printf '// Generated by bindings.sh from cuda.h (CUDA_VERSION %s). Do not edit.\n\n' \
        "$(sed -n 's/^#define CUDA_VERSION \([0-9]*\).*/\1/p' "$include/cuda.h")"
    bindgen "$include/cuda.h" \
        --allowlist-function "($functions)(_v[0-9]+)?" \
        --allowlist-type 'CUstream_flags|CUevent_flags' \
        --allowlist-var 'CUDA_VERSION' \
        --blocklist-function 'cuLaunchHostFunc_v2' \
        --default-enum-style newtype \
        --no-layout-tests \
        --no-doc-comments \
        --use-core \
        -- -I "$include"
} > "$crate/src/sys.rs"
rustfmt --edition 2024 "$crate/src/sys.rs"
